import { StyleSheet } from "react-native";
import { theme } from "../../theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.light,
    padding: 50,
  },
  button: {
    height: 60,
    flexDirection: "row",
    width: "100%",
    backgroundColor: theme.colors.brand,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    marginTop: 30,
  },
  scroll: {
    backgroundColor: theme.colors.light,
  },
  delete: {
    right: -5,
    height: 35,
    width: 100,
    marginTop: 15,
    backgroundColor: theme.colors.red,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
  },
  edit: {
    right: -5,
    height: 35,
    width: 100,
    marginRight: 25,
    marginTop: 15,
    backgroundColor: theme.colors.dark,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
  },
  back: {
    height: 50,
    width: 50,
    backgroundColor: theme.colors.brand,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    marginVertical: 30,
  },
  title: {
    fontSize: 14,
    color: theme.colors.white,
    marginLeft: 20,
  },
  noContent: {
    height: 250,
    position: "relative",
    borderRadius: 15,
    marginTop: 200,
    textAlign: "center",
    justifyContent: "center",
    alignContent: "center",
    borderWidth: 2,
    borderColor: theme.colors.white,
    backgroundColor: theme.colors.brand,
    padding: 20,
  },
  insideFont: { fontSize: 20, fontWeight: "bold", color: theme.colors.white },
  itemList: {
    display: "flex",
    backgroundColor: theme.colors.white,
    borderRadius: 10,
    padding: 20,
    marginBottom: 15,
  },
});
